export const LOAD_CURRENT_USER_REQUESTED = 'LOAD_CURRENT_USER_REQUESTED';
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_FAILED = 'LOAD_CURRENT_USER_FAILED';
