export const SIGN_IN_USER_REQUESTED = 'SIGN_IN_USER_REQUESTED';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILED = 'SIGN_IN_USER_FAILED';

export const CHECK_LOCAL_TOKEN_SUCCESS = 'CHECK_LOCAL_TOKEN_SUCCESS';
export const CHECK_LOCAL_TOKEN_FAILED = 'CHECK_LOCAL_TOKEN_FAILED';

export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';

export const RESET_STATE = 'RESET_STATE';

export const REGISTER_USER_REQUESTED = 'REGISTER_USER_REQUESTED';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
