language: node_js
node_js:
- 8.9.4
install:
- yarn install
script:
- yarn build
notifications:
  email: false
  slack: fhnw-wodss:2eK9ca6usY3orK9hBDdV8vvA
deploy:
  provider: heroku
  api_key:
    secure: zSeMTOrabM9kZPPSXpli/dE6PaLKanPuRKBr2eABrYUxFSGl2t+Fv6gsDk9Hnma6BmGoq8mNwbQvy4CO6m0eVpJmqjL8A1WHct3CGSLk7CA2sLtguibU3osFtWwx5QpVrFLMZl3XeBBFlQkuE3FtAuuf9QHyztPa8/8Y9xG3cXN0cqH0b0qI02lk324KDg+5ooaH4HuIwg14F2hr3guTe3iOELUrLKjxOxHiRs9LQt6+4AeX7otaQumEOgDYPgFW4BnAlYN+3G3O/P6R5ikhEnddTpSuS+amKuTcO4La8XyHyvKoh3DRpvPgPDYCmW571d/drQfyPGhPhNC90c3GWdi9clkIALavBJkYythuzuUd8fiK55SkmrBerVgHlhphclPOkhoIOzON96N8BQYmSaBLbT9x9mEREMYZFE/XDJRSDiUgJkD6ouTXO5/OucsjdkTfGq9Gv24VjJ486qcc5u4suCe3KSrxWT/sXTUx7M6FxjUQoTEqmtK2f+ePJVD4IpHeoE+aE+qGHQwBqEMLWcEFuE8akJjxRYybpwtF70TublveBSPU5RNAl9/5QFF/AnoEckH7uyoFwEVDzCEr6lPDFirtz+QDKA91rYo6lnwS1jN7DTOD/ibAukaoz9G0b1ouEIBDJtRc1Vm15Kdcm3xO+alj6cLoRw2V3E4w25U=
  run: yarn build
  app: wodss-tippspiel-web
    repo: fhnw-students/wodss-tippspiel-web
    branch: feature/deployment
