export const LOAD_INFO_REQUESTED = 'LOAD_INFO_REQUESTED';
export const LOAD_INFO_SUCCESS = 'LOAD_INFO_SUCCESS';
export const LOAD_INFO_FAILED = 'LOAD_INFO_FAILED';

export const SET_SERVER_AVAILABLE = 'SET_SERVER_AVAILABLE';
export const SET_SERVER_UNAVAILABLE = 'SET_SERVER_UNAVAILABLE';
