export const SIGN_IN_USER_REQUESTED = 'SIGN_IN_USER_REQUESTED';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILED = 'SIGN_IN_USER_FAILED';

export const CHECK_AUTH = 'CHECK_AUTH';

export const SIGN_OUT_USER_SUCCESS = 'SIGN_OUT_USER_SUCCESS';

export const RESET_STATE = 'RESET_STATE';
